/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  SearchResult,
} from './components/toob-search/toob-search';
import {
  SearchResult as SearchResult1,
} from './components/toob-search/toob-search';
import {
  VideoStatus,
} from './libs/youtube';

export namespace Components {
  interface ToobApp {}
  interface ToobButton {
    '_hidden'?: boolean;
    'color'?: string;
    'disabled'?: boolean;
    'icon': string;
  }
  interface ToobCheckbox {
    'checked'?: boolean;
  }
  interface ToobSearch {}
  interface ToobVideo {
    'data': SearchResult;
  }
}

declare global {


  interface HTMLToobAppElement extends Components.ToobApp, HTMLStencilElement {}
  var HTMLToobAppElement: {
    prototype: HTMLToobAppElement;
    new (): HTMLToobAppElement;
  };

  interface HTMLToobButtonElement extends Components.ToobButton, HTMLStencilElement {}
  var HTMLToobButtonElement: {
    prototype: HTMLToobButtonElement;
    new (): HTMLToobButtonElement;
  };

  interface HTMLToobCheckboxElement extends Components.ToobCheckbox, HTMLStencilElement {}
  var HTMLToobCheckboxElement: {
    prototype: HTMLToobCheckboxElement;
    new (): HTMLToobCheckboxElement;
  };

  interface HTMLToobSearchElement extends Components.ToobSearch, HTMLStencilElement {}
  var HTMLToobSearchElement: {
    prototype: HTMLToobSearchElement;
    new (): HTMLToobSearchElement;
  };

  interface HTMLToobVideoElement extends Components.ToobVideo, HTMLStencilElement {}
  var HTMLToobVideoElement: {
    prototype: HTMLToobVideoElement;
    new (): HTMLToobVideoElement;
  };
  interface HTMLElementTagNameMap {
    'toob-app': HTMLToobAppElement;
    'toob-button': HTMLToobButtonElement;
    'toob-checkbox': HTMLToobCheckboxElement;
    'toob-search': HTMLToobSearchElement;
    'toob-video': HTMLToobVideoElement;
  }
}

declare namespace LocalJSX {
  interface ToobApp extends JSXBase.HTMLAttributes<HTMLToobAppElement> {}
  interface ToobButton extends JSXBase.HTMLAttributes<HTMLToobButtonElement> {
    '_hidden'?: boolean;
    'color'?: string;
    'disabled'?: boolean;
    'icon'?: string;
    'onOnClick'?: (event: CustomEvent<MouseEvent>) => void;
  }
  interface ToobCheckbox extends JSXBase.HTMLAttributes<HTMLToobCheckboxElement> {
    'checked'?: boolean;
    'onChanged'?: (event: CustomEvent<boolean>) => void;
  }
  interface ToobSearch extends JSXBase.HTMLAttributes<HTMLToobSearchElement> {
    'onFound'?: (event: CustomEvent<SearchResult>) => void;
    'onSearching'?: (event: CustomEvent<string>) => void;
  }
  interface ToobVideo extends JSXBase.HTMLAttributes<HTMLToobVideoElement> {
    'data'?: SearchResult;
    'onStatusUpdate'?: (event: CustomEvent<{video: ToobVideo, status: VideoStatus}>) => void;
  }

  interface IntrinsicElements {
    'toob-app': ToobApp;
    'toob-button': ToobButton;
    'toob-checkbox': ToobCheckbox;
    'toob-search': ToobSearch;
    'toob-video': ToobVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


